name: Run Tests
on:
  pull_request: 
    paths: ["src/**/*.*", "tests/**/*.*", "Cargo.toml", "Cargo.lock"]

jobs:
  lint:
    name: Lint / Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Install rust
        uses: moonrepo/setup-rust@v1

      - run: rustup component add rustfmt
      - name: Run fmt
        run: cargo fmt --all -- --check

      - run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy -- -D warnings
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Install rust
        uses: moonrepo/setup-rust@v1
      
      - run: cargo test